apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  annotations:
    cloud.google.com/backend-config: '{"default": "api-gateway-config"}'
spec:
  selector:
    app: api-gateway
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP