apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api-gateway-config
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: "/api/healthz"
  timeoutSec: 30