apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: frontend-config
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: "/"
  timeoutSec: 30