name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ "api-gateway", "admin-service", "ride-service", "notification-service", "review-service", "user-service" ]
    steps:
      - name: Checkout repository including submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Install dependencies for ${{ matrix.service }}
        run: |
          if [ -f "services/${{ matrix.service }}/pyproject.toml" ]; then
            cd services/${{ matrix.service }}
            uv sync --dev
            cd -
          fi

      - name: Run tests for ${{ matrix.service }}
        run: |
          if [ -d "services/${{ matrix.service }}/tests" ]; then
            cd services/${{ matrix.service }}
            uv run pytest
            cd -
          fi